{
 "title": "Jogo Enigma – Observabilidade HOMOL",
 "tags": [
  "A2",
  "HOMOL"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status da API",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jogo-enigma-api\"}"
    }
   ]
  },
  {
   "title": "Memória JVM – Heap",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Requisições HTTP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  }
 ]
}